files:
  - "train-00000-of-00645-b66ac786bf6fb553.parquet"
mlp:
  periodicity: null
  rescale_output: False
  scale: 2.0
  width: 10
  layers: 2
  segments: 2

embedding_size: 384 # Text embedding size
input_size: 10 # Actually the input size of mlp
output_size: 3 # rgb
input_segments: 20 # number of segments for x,y position
layer_type: "continuous"
n: 3

max_epochs: 50
gpus: 1
accelerator : cuda
lr: 1e-3
batch_size: 256

# Are you training? Otherwise plot the result
train: True
checkpoint: null
rotations: 1 # 1 is x,y, 2 is x,y, x-y, x+y, greater includes additional rotations

defaults:
  - optimizer: sparse_lion
