images :
  - "images/newt.jpg"
  - "images/jupiter.jpg"
mlp :
  layer_type : "polynomial"
  n : 2
  periodicity : null
  rescale_output : False
  scale : 2.0
  input :
    segments : 1
    width : 2
  output :
    segments : 1
    width : 3
  hidden :
    segments : 1
    layers : 2
    width : 10

max_epochs: 100
gpus: 0
lr: 1e-3
batch_size: 32